name: bdaya_firebase_helpers
description: A new Flutter package project.
version: 1.0.0
repository: https://github.com/Bdaya-Dev/bdaya_firebase_helpers

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  get: ^4.1.4
  cloud_firestore: ^1.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
